python3 train.py \
--train_config /Users/pecholalee/Coding/IDEAW/config.yaml \
--model_config /Users/pecholalee/Coding/IDEAW/models/config.yaml \
--data_config /Users/pecholalee/Coding/IDEAW/data/config.yaml \
--pickle_path /Users/pecholalee/Coding/Watermark/miniAWdata_pickle/audio.pkl \
--store_model_path /Users/pecholalee/Coding/Watermark/ideaw_data/save/ \
--load_model_path /Users/pecholalee/Coding/Watermark/ideaw_data/save/ \
--summary_steps 2 \
--save_steps 5 \
--iterations 10 \
